version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: my-secret-password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - /home/universidad/U/BD/mysql:/var/lib/postgresql/data
