version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_empresa
    ports:
      - "3306:3306"
    volumes:
      - /home/universidad/U/BD/mysql:/var/lib/mysql
